apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kafka-secret
  namespace: openshift-logging
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: ca-bundle.crt
    secretKey: ca-bundle.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: password
    secretKey: password
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: sasl.enable
    secretKey: sasl.enable
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: sasl.mechanism
    secretKey: sasl.mechanism
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: security.protocol
    secretKey: security.protocol
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: tls.ca_file
    secretKey: tls.ca_file
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: openshift-logging/kafka-secret
      property: username
    secretKey: username
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: kafka-secret
