apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
bases:
- ../../base
secretGenerator:
- name: htpass-secret
  type: Opaque
  files:
  - users.htpasswd
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated-disabled-suffix
  annotations:
    note: generated-disabled-suffix
