apiVersion: v1
kind: Namespace
metadata:
  name: openshift-kube-descheduler-operator
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    openshift.io/cluster-monitoring: "true"
