apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wildcard-cert
  namespace: openshift-ingress
spec:
  data:
  - remoteRef:
      key: openshift-ingress/apps-cert.ocplandev
      property: tls.crt
    secretKey: tls.crt
  - remoteRef:
      key: openshift-ingress/apps-cert.ocplandev
      property: tls.key
    secretKey: tls.key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: apps.cert.ocplandev