apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- loki-sub-acm.yaml
- clusterlogforwarder.yaml
secretGenerator:
  - name: logging-loki-odf
    namespace: openshift-logging
    literals:
    - access_key_id=YSY34JHdxgmWczeSViZF
    - access_key_secret=6o31WvqaG5t3ht+F/nVWBTKa2W9IgY2iPZz4SxW8
    - bucketnames=loki-bucket-odf-4919b4a2-cbad-4cce-bf7a-c4cccce07346
    - endpoint=https://s3.openshift-storage.svc:443
generatorOptions:
  disableNameSuffixHash: true
 
