apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFlTCCA32gAwIBAgITbwAAAAPelCoPT190kQAAAAAAAzANBgkqhkiG9w0BAQsF
    xiSj/5n9QuJOTAV9hXGMP4LmanUDpZxOcM+X405Hs+QiSpEwUCMABhQ=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: openshift-config
