apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-backup
  namespace: ocp-etcd-backup
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - Get
  - List
  - Watch
  - Patch
