apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: 
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: htpass-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sudoer
subjects:
- kind: User
  name: ocp-bob, ocp-marina
userNames:
- ocp-bob, ocp-marina
