apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
spec:
  identityProviders:
  - ldap:
      attributes:
        email:
        - mail
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: CN=ocp-p-ldap,OU=OpenshiftProd,OU=Sensitive Accounts,OU=Global Prod
          Resources,OU=Prod Environments,OU=Maccabi-Root,DC=mac,DC=org,DC=il
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldaps://mac.org.il:636/dc=mac,dc=org,dc=il?sAMAccountName
    mappingMethod: claim
    name: ldapidp
    type: LDAP
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: htpasswd-provider
    type: HTPasswd
