apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: v4-0-config-user-idp-0-ca
  namespace: openshift-authentication
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: v4-0-config-user-idp-0-bind-password
  namespace: openshift-authentication
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: v4-0-config-user-idp-1-file-data
#  namespace: openshift-authentication
