apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-controller-admin-password
  namespace: aap
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aap/aap-admin
      property: password
    secretKey: password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aap-controller-admin-password

