apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: aap-controller
  namespace: aap
spec:
  admin_user: admin
  auto_upgrade: true
  bundle_cacert_secret: ca-bundle-custom-certs-maccabi
  create_preload_data: true
  extra_settings:
  - setting: AUTH_LDAP_SERVER_URI
    value: '"ldaps://mac.org.il:636"'
  - setting: AUTH_LDAP_BIND_DN
    value: '"CN=ocp-t-ldap,OU=OpenShiftNP,OU=Sensitive Accounts,OU=Non-Prod Environments,OU=Maccabi-Root,DC=mac,DC=org,DC=il"'
  - setting: AUTH_LDAP_USER_SEARCH
    value: LDAPSearch( "DC=mac,DC=org,DC=il","SCOPE_SUBTREE","(sAMAccountName=%(user)s)",)
  - setting: AUTH_LDAP_GROUP_SEARCH
    value: LDAPSearch("DC=mac,DC=org,DC=il","SCOPE_SUBTREE","(objectClass=group)",)
  - setting: AUTH_LDAP_GROUP_TYPE
    value: MemberDNGroupType(name_attr="cn",member_attr="member")
  - setting: AUTH_LDAP_BIND_PASSWORD
    value: '"ShiftOpen1990000"'
  - setting: AUTH_LDAP_USER_ATTR_MAP
    value: '''{"first_name": "givenName","last_name": "sn","email": "mail"}'''
  - setting: AUTH_LDAP_USER_FLAGS_BY_GROUP
    value:
      is_superuser:
      - CN=LinuxTeam,OU=Security,OU=Groups,OU=Global Prod Resources,OU=Prod Environments,OU=Maccabi-Root,DC=mac,DC=org,DC=il
  - setting: AUTH_LDAP_ORGANIZATION_MAP
    value:
      Linux Team:
        admins: CN=LinuxTeam,OU=Security,OU=Groups,OU=Global Prod Resources,OU=Prod
          Environments,OU=Maccabi-Root,DC=mac,DC=org,DC=il
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  ingress_type: Route
  ipv6_disabled: false
  postgres_configuration_secret: aap-controller-postgres-configuration 
  secret_key_secret: aap-controller-secret-key 
  ldap_cacert_secret: ca-bundle-custom-certs-maccabi
  ldap_password_secret: aap-ldap-password
  loadbalancer_ip: ""
  loadbalancer_port: 80
  loadbalancer_protocol: http
  no_log: true
  postgres_keepalives: true
  postgres_keepalives_count: 5
  postgres_keepalives_idle: 5
  postgres_keepalives_interval: 5
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 2
  route_tls_termination_mechanism: Edge
  set_self_labels: true
  task_privileged: false
