apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ca-bundle-custom-certs-maccabi
  namespace: aap
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aap/ca-bundle
      property: bundle-ca.crt
    secretKey: bundle-ca.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aap/ca-bundle
      property: ldap-ca.crt
    secretKey: ldap-ca.crt
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: ca-bundle-custom-certs-maccabi

