apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-ldap-password
  namespace: aap
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aap/ldap-password
      property: ldap-password
    secretKey: ldap-password
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aap-ldap-password

