apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aap-controller-secret-key
  namespace: aap
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: aap/secret-key
      property: secret_key
    secretKey: secret_key
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: aap-controller-secret-key

