apiVersion: nmstate.io/v1 
kind: NodeNetworkConfigurationPolicy 
metadata: 
 name: infra05-dns-fix 
spec: 
  nodeSelector: 
    kubernetes.io/hostname: ocp-p-inf05.ocplanprod.mac.org.il
  desiredState:
    dns-resolver:
      config:
        search:
        - ocplanprod.mac.org.il
        - mac.org.il
        server:
        - 10.74.1.201
        - 10.74.1.204
