apiVersion: nmstate.io/v1 
kind: NodeNetworkConfigurationPolicy 
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: infra04-dns-fix 
spec: 
  nodeSelector: 
    kubernetes.io/hostname: ocp-t-inf04.ocplantest.oranization.domain
  desiredState:
    dns-resolver:
      config:
        search:
        - ocplantest.oranization.domain
        - oranization.domain
        server:
        - 10.74.1.201
        - 10.74.1.204
