apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- loki-sub-dev.yaml
- clusterlogforwarder.yaml
secretGenerator:
  - name: logging-loki-odf
    namespace: openshift-logging
    literals:
    - access_key_id=ZsHt0CzJOMy77oUmLhcz
    - access_key_secret=L8Fc7QK+BLEMxOi5R9t1GVjCfcZcOu5zy0YAqj5S
    - bucketnames=loki-bucket-odf-ce2834a0-ea79-46e5-a95f-48ea1116058c
    - endpoint=https://s3.openshift-storage.svc:443
generatorOptions:
  disableNameSuffixHash: true
