apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    olm.providedAPIs: Jaeger.v1.jaegertracing.io
  generateName: openshift-distributed-tracing-
  name: openshift-distributed-tracing
  namespace: openshift-distributed-tracing
spec:
  upgradeStrategy: Default
  targetNamespaces:
  - ""

