apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: CN=ocp-d-ldap,OU=OpenShiftNP,OU=Sensitive Accounts,OU=Non-Prod Environments,OU=Organization-Root,DC=mac,DC=org,DC=il
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldaps://oranization.domain:636/dc=mac,dc=org,dc=il?sAMAccountName?sub?(&(objectClass=user)(memberOf=CN=openshiftusers-dev,OU=dev,OU=Openshift,OU=Security,OU=Groups,OU=Global
        Prod Resources,OU=Prod Environments,OU=Organization-Root,DC=mac,DC=org,DC=il)(!userAccountControl:1.2.840.113556.1.4.803:=2))
    mappingMethod: claim
    name: ldapad
    type: LDAP
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: htpasswd-provider
    type: HTPasswd
  - htpasswd:
      fileData:
        name: htpasswd-eclipse-che
    mappingMethod: claim
    name: htpasswd-eclipse-che
    type: HTPasswd

