apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- loki-sub-qa.yaml
- clusterlogforwarder.yaml
secretGenerator:
  - name: logging-loki-odf
    namespace: openshift-logging
    literals:
    - access_key_id=rIPsEiv4xDBehGbJH1Rb
    - access_key_secret=VrwffrypZx4gnEiFsC5Tv2Q8CAPt1dFdj7eCtzd0
    - bucketnames=loki-bucket-odf-c5ac9807-02f0-4d88-8689-04f143245a05
    - endpoint=https://s3.openshift-storage.svc:443
generatorOptions:
  disableNameSuffixHash: true  
