apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitops-primer
  namespace: gitops-primer-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  channel: alpha
  installPlanApproval: Automatic 
  name: gitops-primer
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gitops-primer.v0.0.11 
