apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dynatrace
  namespace: dynatrace
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  upgradeStrategy: Default
