apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - ldap:
      attributes:
        email: []
        id:
        - dn
        name:
        - cn
        preferredUsername:
        - sAMAccountName
      bindDN: CN=ocp-acm-ldap,OU=OpenshiftProd,OU=Sensitive Accounts,OU=Global Prod Resources,OU=Prod Environments,OU=Organization-Root,DC=organization,DC=org,DC=il
      bindPassword:
        name: ldap-secret
      ca:
        name: ca-config-map
      insecure: false
      url: ldaps://oranization.domain:636/dc=organization,dc=org,dc=il?sAMAccountName
    mappingMethod: claim
    name: ldap
    type: LDAP
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: htpasswd
    type: HTPasswd
 
