apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: dynatrace/dynakube
      property: apiToken
    secretKey: password
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: dynatrace/dynakube
      property: dataIngestToken
    secretKey: dataIngestToken
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: dynakube

